steps=input("enter the number of steps sperator by space : ")
steps_list=list(map(int,steps.split()))
max_step=max(steps_list)
min_step=min(steps_list)
average_step=sum(steps_list)/len(steps_list)
order_steps=sorted(steps_list,reverse=True)
print("max: ",max_step)
print("min: ",min_step)
print("avg: ",average_step)
print("the step counts in descending order",order_steps)